apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaniko-actions-pod
  labels:
    app.kubernetes.io/name: kaniko-actions-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kaniko-actions-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kaniko-actions-pod
    spec:
      containers:
        - name: kaniko-actions-pod
          image: harbor.lakis.eu/mysterycamp/kaniko-actions-pod:0.0.1
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: kaniko-actions-pod
